FROM golang:1.22-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
WORKDIR /app/cmd/api
RUN CGO_ENABLED=0 GOOS=linux GOFLAGS="-buildvcs=false" go build -ldflags="-s -w" -o /app/api .

FROM scratch
WORKDIR /app
COPY --from=builder /app/api .
ENV PORT=8080
ENV GIN_MODE=release
EXPOSE 8080
ENTRYPOINT ["/app/api"]