apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-frontend
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-frontend
  template:
    metadata:
      labels:
        app: nextjs-frontend
    spec:
      containers:
        - name: nextjs-frontend
          image: nextjs-frontend:latest
          imagePullPolicy: Never  # Use the local image
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: "http://go-api-service.web-app.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: web-app
spec:
  selector:
    app: nextjs-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP