apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-frontend
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-frontend
  template:
    metadata:
      labels:
        app: nextjs-frontend
    spec:
      containers:
        - name: nextjs-frontend
          image: pocwebapp/front-poc-web-app-othman-martin:latest
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: "http://go-api-service.web-app.svc.cluster.local"